### ISSUE TITLE
[BUG] TMDBH Error Thrown When Scrolling Over Accounts Tab in Umbrella Settings

### ISSUE THREAD

**Issue by rtuRgALp** [jurialmunkey/plugin.video.themoviedb.helper#919]
### Describe the bug

Whenever I have Umbrella and TMDBH installed together, when I scroll over the Accounts tab in the Settings Menu of Umbrella, an error is thrown.

This happens on my MacBook Air and Apple TV 4K. 

### Steps To Reproduce

To reproduce, open Kodi, install TMDBH from jurialmunkey Alpha repo, install Umbrella from umbrellaplug repo, and open Umbrella settings Menu and scroll over Accounts tab.

### Debug log

https://paste.kodi.tv/egixacokex

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Fairly sure this has been fixed.
