### ISSUE TITLE
pvr artwork/meta data missing

### ISSUE THREAD

**Issue by s0ulslack** [jurialmunkey/plugin.video.themoviedb.helper#941]
### Describe the bug

It seems right around 5.0.11 these features quit working 

### Steps To Reproduce

Use >5.0.11 and no pvr art/metadata is stored

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
PVR lookups work fine for me in AH2. I'll need much more information than just "doesn't work".
